Added html / About section
katefranchuk/ice-cream-landing pull request #3
Opened 2022-11-22 22:35 UTC by HannaTubolets

2022-11-23 05:34 UTC, katefranchuk requested changes

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +<section class="about">
додай ще клас section, він вже прописаний у _reusable-classes.scss

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +  <p class="about__pre-heading">Tradition and love</p>
додай ще клас .section__description, він вже прописаний у _reusable-classes.scss

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +  <h2 class="adout__heading">How it’s made?</h2>
додай ще клас .section__title,  він вже прописаний у _reusable-classes.scss
ці класи поворюються у деяких секціях

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +<section class="about">
пісяля < section > додаємо < div class="container" >< /div >

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +    <button type="button" class="btn-main">Read more</button>
спробуєш вже при оформленні css додати клас btn btn--fill з  _reusable-classes.scss

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +  <div class="about__img-wrap">
about__img-wrap та about__info мають бути обгорнуті div

2022-11-23 05:34 UTC, katefranchuk commented on src/partials/about.html
> +    <img
можег додати тег picture (в ньому вже тег img), щоб помістити усі 6 картинок
тоді ширина і висота будуть непотрібні

2022-11-23 05:34 UTC, katefranchuk commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
ці всі речі є у папці sass > base
не розумію чому в тебе в папці sass файли css

2022-11-23 06:39 UTC, HannaTubolets commented on src/partials/about.html
> +<section class="about">
додано

2022-11-23 06:40 UTC, HannaTubolets commented on src/partials/about.html
> +  <p class="about__pre-heading">Tradition and love</p>
додано

2022-11-23 06:40 UTC, HannaTubolets commented on src/partials/about.html
> +  <h2 class="adout__heading">How it’s made?</h2>
додано

2022-11-23 06:40 UTC, HannaTubolets commented on src/partials/about.html
> +<section class="about">
додано

2022-11-23 06:40 UTC, HannaTubolets commented on src/partials/about.html
> +    <button type="button" class="btn-main">Read more</button>
ок

2022-11-23 06:41 UTC, HannaTubolets commented on src/partials/about.html
> +  <div class="about__img-wrap">
ок

2022-11-23 06:45 UTC, HannaTubolets commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
Не знаю, склонувала репозиторій, файли не перетягувала/ не додавала...

2022-11-23 06:56 UTC, HannaTubolets commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
Виходить, що у вихідному репозиторії склонованому немає папки css і файли лежать в sass.
Тому у мене і не підтягуються базові стилі, які вже прописані в base(

2022-11-24 12:38 UTC, katefranchuk approved these changes

2022-11-24 12:38 UTC, merged